import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export type AppLanguage = 'bg' | 'en';

const STORAGE_KEY = 'aurelia-language';

const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  bg: {
    'nav.reservations': 'Резервации',
    'nav.vip': 'VIP',
    'nav.schedule': 'График',
    'nav.control': 'Контрол',
    'nav.bookings': 'Записвания',
    'nav.services': 'Услуги',
    'nav.locations': 'Локации',
    'nav.users': 'Потребители',
    'nav.signOut': 'Изход',
    'nav.darkMode': 'Нощен режим',
    'nav.lightMode': 'Дневен режим',
    'role.customer': 'КЛИЕНТ',
    'role.vip': 'VIP',
    'role.employee': 'СЛУЖИТЕЛ',
    'role.admin': 'АДМИН',

    'login.heroTitle': 'Aurelia Spa Platform',
    'login.heroLead': 'Лесно резервиране, любими услуги и спокойствие за вашето време за почивка.',
    'login.metric1Title': 'Умно планиране',
    'login.metric1Desc': 'Запишете услуга и час за секунди.',
    'login.metric2Title': 'Клиентски профили',
    'login.metric2Desc': 'История и предпочитания на едно място.',
    'login.metric3Title': 'Премиум локации',
    'login.metric3Desc': 'Изберете обект близо до вас.',
    'login.signIn': 'Вход',
    'login.signInSub': 'Влезте в клиентския портал.',
    'login.tabSignIn': 'Вход',
    'login.tabRegister': 'Регистрация',
    'login.username': 'Потребителско име',
    'login.password': 'Парола',
    'login.name': 'Име',
    'login.email': 'Имейл',
    'login.phone': 'Телефон',
    'login.enter': 'Влез',
    'login.guest': 'Вход като гост',
    'login.registerSub': 'Създайте клиентски профил.',
    'login.registerBtn': 'Създай профил',
    'login.registerSuccess': 'Профилът е създаден. Влезте с новите данни.',
    'login.registerFailed': 'Регистрацията не бе успешна.',
    'login.registerConflict': 'Потребител с тези данни вече съществува.',
    'login.registerValidation': 'Попълнете коректно всички полета.',
    'login.usernameTaken': 'Това потребителско име вече е заето.',
    'login.emailTaken': 'Този имейл вече се използва.',
    'login.invalidCredentials': 'Невалидни данни за вход',
    'login.guestFailed': 'Неуспешен гост вход',
    'login.showPassword': 'Покажи парола',
    'login.hidePassword': 'Скрий парола',

    'customer.eyebrow': 'Клиентски портал',
    'customer.title': 'Планирайте следващото си посещение',
    'customer.lead': 'Вижте наличности и потвърдете записванията си.',
    'customer.member': 'Клиент',
    'customer.status': 'Статус',
    'customer.statusVip': 'VIP одобрен',
    'customer.statusStandard': 'Стандартен',
    'customer.guest': 'Гост',
    'customer.fastFlowTitle': 'Бърз процес на резервация',
    'customer.fastFlowLead': 'Изберете услуга, служител и локация.',
    'customer.fastFlowChip': 'Промените се обновяват веднага',
    'customer.priceChartDownload': 'Изтегли ценоразпис',
    'customer.priceChartUnavailable': 'Ценоразписът все още не е качен.',
    'customer.newReservation': 'Нова резервация',
    'customer.newReservationLead': 'Изберете услуга, специалист и локация.',
    'customer.timesLocal': 'Часовете са локални',
    'customer.fieldCustomer': 'Клиент',
    'customer.fieldService': 'Услуга',
    'customer.fieldEmployee': 'Предпочитан служител',
    'customer.fieldLocation': 'Локация',
    'customer.fieldDay': 'Ден',
    'customer.fieldSession': 'Свободни сесии',
    'customer.fieldStart': 'Начало',
    'customer.fieldEnd': 'Край',
    'customer.slotOccupied': 'Заето',
    'customer.slotPast': 'Изминал час',
    'customer.slotSelected': 'Избран час',
    'customer.slotChooseDateEmployee': 'Изберете служител и ден, за да видите разписанието.',
    'customer.selectService': 'Изберете услуга',
    'customer.selectEmployee': 'Изберете служител',
    'customer.selectLocation': 'Изберете локация',
    'customer.noAddress': 'Няма въведен адрес',
    'customer.loggedCustomer': 'Влязъл клиент',
    'customer.confirmReservation': 'Потвърди резервация',
    'customer.myReservations': 'Моите резервации',
    'customer.myReservationsLead': 'Следете и отменяйте при нужда.',
    'customer.reservationsWord': 'резервации',
    'customer.noReservations': 'Все още нямате резервации.',
    'customer.membershipUpgrade': 'VIP членство',
    'customer.membershipUpgradeLead': 'Кандидатствайте за приоритетно записване.',
    'customer.adminReview': 'Администраторска проверка',
    'customer.vipApprovedTitle': 'Одобрено',
    'customer.vipApprovedLead': 'Вече имате VIP достъп.',
    'customer.vipPendingTitle': 'В процес',
    'customer.vipPendingLead': 'Заявката ви се разглежда.',
    'customer.vipRejectedTitle': 'Не е одобрено',
    'customer.vipRejectedLead': 'Може да кандидатствате отново с повече детайли.',
    'customer.vipReason': 'Причина за VIP заявка',
    'customer.vipPlaceholder': 'Опишете предпочитани услуги или удобен график.',
    'customer.sendVip': 'Изпрати заявка',
    'customer.cancel': 'Откажи',
    'customer.date': 'Дата',
    'customer.location': 'Локация',
    'customer.with': 'с',
    'customer.errorRequired': 'Попълнете всички задължителни полета.',
    'customer.errorBookingFailed': 'Резервацията не бе успешна. Опитайте отново.',
    'customer.bookingCreated': 'Резервацията е потвърдена.',
    'customer.errorGuestBooking': 'Резервации са достъпни след вход в профил.',
    'customer.errorVipLogin': 'Трябва да сте влезли в профил, за да кандидатствате.',
    'customer.errorVipNote': 'Добавете кратка бележка към заявката.',
    'customer.confirmCancel': 'Да отменя ли тази резервация?',

    'employee.eyebrow': 'Екипен график',
    'employee.title': 'Календар на услугите',
    'employee.lead': 'Следете предстоящите часове и работете спокойно.',
    'employee.employee': 'Служител',
    'employee.teamMember': 'Член на екипа',
    'employee.view': 'Изглед',
    'employee.upcomingView': 'Само предстоящи',
    'employee.allView': 'Всички',
    'employee.filterUpcoming': 'Само предстоящи',
    'employee.filterAll': 'Всички записвания',
    'employee.noBookings': 'Няма записвания за този период.',
    'employee.customer': 'Клиент',
    'employee.location': 'Локация',
    'employee.window': 'Период',
    'employee.remaining': 'Оставащо време',

    'admin.eyebrow': 'Оперативен център',
    'admin.title': 'Системна администрация',
    'admin.lead': 'Управлявайте достъпи, потребители и одобрения.',
    'admin.roles': 'Роли',
    'admin.users': 'Потребители',
    'admin.vipRequests': 'VIP заявки',
    'admin.roleAndViews': 'Роли и изгледи',
    'admin.userOverview': 'Преглед на потребители',
    'admin.vipTab': 'VIP заявки',
    'admin.createAdminTab': 'Създай админ',
    'admin.usersTab': 'Потребители',
    'admin.bookingsTab': 'Резервации',
    'admin.servicesTab': 'Услуги',
    'admin.locationsTab': 'Локации',
    'admin.refresh': 'Обнови',
    'admin.partialLoad': 'Част от данните не се заредиха. Опитайте отново.',
    'admin.roleManagement': 'Управление на роли',
    'admin.cancel': 'Отказ',
    'admin.addRole': 'Добави нова роля',
    'admin.roleName': 'Име на роля',
    'admin.roleNamePlaceholder': 'напр. CUSTOMER_PLUS',
    'admin.roleView': 'Изглед',
    'admin.description': 'Описание',
    'admin.noDescription': 'Няма описание',
    'admin.adminAccess': 'Админ достъп',
    'admin.createRole': 'Създай роля',
    'admin.updateRole': 'Обнови роля',
    'admin.requiredRoleFields': 'Попълнете задължителните полета.',
    'admin.roleSaveFailed': 'Неуспешно запазване на роля.',
    'admin.roleSaved': 'Ролята е запазена.',
    'admin.roleDeleted': 'Ролята е изтрита.',
    'admin.roleDeleteFailed': 'Ролята не може да бъде изтрита.',
    'admin.roleDescriptionPlaceholder': 'Кратко описание на ролята',
    'admin.yes': 'Да',
    'admin.no': 'Не',
    'admin.actions': 'Действия',
    'admin.assignedView': 'Изглед',
    'admin.vip': 'VIP',
    'admin.edit': 'Редакция',
    'admin.delete': 'Изтрий',
    'admin.areYouSure': 'Сигурни ли сте?',
    'admin.noPendingVip': 'Няма чакащи VIP заявки.',
    'admin.approve': 'Одобри',
    'admin.reject': 'Откажи',
    'admin.vipApprovedToast': 'VIP заявката е одобрена.',
    'admin.vipRejectedToast': 'VIP заявката е отказана.',
    'admin.createAdmin': 'Създай нов администратор',
    'admin.username': 'Потребителско име',
    'admin.password': 'Парола',
    'admin.name': 'Име',
    'admin.email': 'Имейл',
    'admin.phone': 'Телефон',
    'admin.createAdminBtn': 'Създай админ',
    'admin.completeAdminFields': 'Попълнете всички админ полета.',
    'admin.createAdminFailed': 'Създаването на админ е неуспешно.',
    'admin.adminCreated': 'Администраторът е създаден.',
    'admin.editUser': 'Редакция на потребител',
    'admin.addUser': 'Добави потребител',
    'admin.createUser': 'Създай нов потребител',
    'admin.createUserBtn': 'Създай потребител',
    'admin.roleLabel': 'Роля',
    'admin.selectRole': 'Изберете роля',
    'admin.passwordOptional': 'Нова парола (по избор)',
    'admin.passwordOptionalHint': 'Оставете празно, за да не се сменя',
    'admin.completeUserFields': 'Попълнете коректно полетата за потребителя.',
    'admin.updateUser': 'Запази потребител',
    'admin.userSaved': 'Потребителят е запазен.',
    'admin.userSaveFailed': 'Неуспешно запазване на потребителя.',
    'admin.userDeleted': 'Потребителят е изтрит.',
    'admin.userDeleteFailed': 'Потребителят не може да бъде изтрит.',
    'admin.bookingsManager': 'Управление на резервации',
    'admin.customer': 'Клиент',
    'admin.employee': 'Служител',
    'admin.serviceLabel': 'Услуга',
    'admin.locationLabel': 'Локация',
    'admin.selectCustomer': 'Изберете клиент',
    'admin.selectEmployee': 'Изберете служител',
    'admin.selectService': 'Изберете услуга',
    'admin.selectLocation': 'Изберете локация',
    'admin.completeBookingFields': 'Попълнете всички полета за резервацията.',
    'admin.createBooking': 'Създай резервация',
    'admin.updateBooking': 'Обнови резервация',
    'admin.bookingSaved': 'Резервацията е запазена.',
    'admin.bookingSaveFailed': 'Неуспешно запазване на резервация.',
    'admin.confirmDeleteBooking': 'Да изтрия ли тази резервация?',
    'admin.bookingDeleted': 'Резервацията е изтрита.',
    'admin.bookingDeleteFailed': 'Резервацията не може да бъде изтрита.',
    'admin.servicesManager': 'Управление на услуги',
    'admin.serviceName': 'Име на услуга',
    'admin.price': 'Цена',
    'admin.vipOnly': 'Само за VIP',
    'admin.completeServiceFields': 'Попълнете всички полета за услугата.',
    'admin.createService': 'Създай услуга',
    'admin.updateService': 'Обнови услуга',
    'admin.serviceSaved': 'Услугата е запазена.',
    'admin.serviceSaveFailed': 'Неуспешно запазване на услуга.',
    'admin.confirmDeleteService': 'Да изтрия ли тази услуга?',
    'admin.serviceDeleted': 'Услугата е изтрита.',
    'admin.serviceDeleteFailed': 'Услугата не може да бъде изтрита.',
    'admin.priceChartSelect': 'Избери PDF ценоразпис',
    'admin.priceChartUpload': 'Качи PDF',
    'admin.priceChartDownload': 'Изтегли PDF',
    'admin.priceChartOnlyPdf': 'Можете да качвате само PDF файл.',
    'admin.priceChartPickFile': 'Изберете PDF файл за качване.',
    'admin.priceChartUploadSuccess': 'Ценоразписът е качен успешно.',
    'admin.priceChartUploadFailed': 'Качването на ценоразписа не бе успешно.',
    'admin.priceChartNotFound': 'Няма качен ценоразпис за изтегляне.',
    'admin.locationsManager': 'Управление на локации',
    'admin.locationName': 'Име на локация',
    'admin.locationAddress': 'Адрес',
    'admin.noAddress': 'Няма въведен адрес',
    'admin.vipServicesAvailable': 'VIP услуги налични',
    'admin.completeLocationFields': 'Попълнете полетата за локацията.',
    'admin.createLocation': 'Създай локация',
    'admin.updateLocation': 'Обнови локация',
    'admin.locationSaved': 'Локацията е запазена.',
    'admin.locationSaveFailed': 'Неуспешно запазване на локация.',
    'admin.confirmDeleteLocation': 'Да изтрия ли тази локация?',
    'admin.locationDeleted': 'Локацията е изтрита.',
    'admin.locationDeleteFailed': 'Локацията не може да бъде изтрита.',

    'vip.tag': 'Премиум портал',
    'vip.title': 'Приоритетен достъп',
    'vip.lead': 'Записвайте се с преференциални цени и приоритетни часове.',
    'vip.member': 'Клиент',
    'vip.guest': 'VIP гост',
    'vip.discount': 'Отстъпка',
    'vip.downloadMenu': 'Изтегли меню',
    'vip.newReservation': 'Нова премиум резервация',
    'vip.newReservationLead': 'Изберете услуга, служител и локация.',
    'vip.reserve': 'Резервирай',
    'vip.premiumServices': 'Премиум услуги',
    'vip.premiumServicesLead': 'Цените са с VIP отстъпка.',
    'vip.servicesWord': 'услуги',
    'vip.myReservations': 'Моите резервации',
    'vip.myReservationsLead': 'Предстоящи премиум записвания.',
    'vip.reservedWord': 'запазени',
    'vip.none': 'Нямате премиум резервации.',
    'vip.save': 'Спестявате',
    'vip.badge': 'VIP',
    'vip.completeFields': 'Попълнете всички полета за резервация.',
    'vip.bookingFailed': 'Резервацията не бе успешна. Опитайте отново.',
    'vip.cancelConfirm': 'Да отменя ли тази резервация?',
    'vip.priceChartUnavailable': 'Ценоразписът все още не е качен.',

    'redirect.preparing': 'Подготвяме вашия профил...'
  },
  en: {
    'nav.reservations': 'Reservations',
    'nav.vip': 'VIP',
    'nav.schedule': 'Schedule',
    'nav.control': 'Control',
    'nav.bookings': 'Bookings',
    'nav.services': 'Services',
    'nav.locations': 'Locations',
    'nav.users': 'Users',
    'nav.signOut': 'Sign out',
    'nav.darkMode': 'Dark mode',
    'nav.lightMode': 'Light mode',
    'role.customer': 'CUSTOMER',
    'role.vip': 'VIP',
    'role.employee': 'EMPLOYEE',
    'role.admin': 'ADMIN',

    'login.heroTitle': 'Aurelia Spa Platform',
    'login.heroLead': 'Fast reservations, favorite services, and a calm customer-first experience.',
    'login.metric1Title': 'Smart Scheduling',
    'login.metric1Desc': 'Book your service and time in seconds.',
    'login.metric2Title': 'Client Profiles',
    'login.metric2Desc': 'History and preferences in one place.',
    'login.metric3Title': 'Premium Locations',
    'login.metric3Desc': 'Choose a spa location near you.',
    'login.signIn': 'Sign in',
    'login.signInSub': 'Access the customer portal.',
    'login.tabSignIn': 'Sign in',
    'login.tabRegister': 'Register',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.name': 'Name',
    'login.email': 'Email',
    'login.phone': 'Phone',
    'login.enter': 'Enter',
    'login.guest': 'Continue as guest',
    'login.registerSub': 'Create a customer account.',
    'login.registerBtn': 'Create account',
    'login.registerSuccess': 'Account created. Sign in with your new credentials.',
    'login.registerFailed': 'Registration failed.',
    'login.registerConflict': 'An account with these details already exists.',
    'login.registerValidation': 'Please complete all fields correctly.',
    'login.usernameTaken': 'This username is already taken.',
    'login.emailTaken': 'This email is already in use.',
    'login.invalidCredentials': 'Invalid credentials',
    'login.guestFailed': 'Guest login failed',
    'login.showPassword': 'Show password',
    'login.hidePassword': 'Hide password',

    'customer.eyebrow': 'Customer Portal',
    'customer.title': 'Plan your next visit',
    'customer.lead': 'Check availability and confirm your bookings.',
    'customer.member': 'Member',
    'customer.status': 'Status',
    'customer.statusVip': 'VIP approved',
    'customer.statusStandard': 'Standard',
    'customer.guest': 'Guest',
    'customer.fastFlowTitle': 'Fast booking flow',
    'customer.fastFlowLead': 'Choose service, employee, and location.',
    'customer.fastFlowChip': 'Changes sync instantly',
    'customer.priceChartDownload': 'Download price chart',
    'customer.priceChartUnavailable': 'Price chart is not uploaded yet.',
    'customer.newReservation': 'New reservation',
    'customer.newReservationLead': 'Select service, specialist, and location.',
    'customer.timesLocal': 'All times are local',
    'customer.fieldCustomer': 'Customer',
    'customer.fieldService': 'Service',
    'customer.fieldEmployee': 'Preferred employee',
    'customer.fieldLocation': 'Location',
    'customer.fieldDay': 'Day',
    'customer.fieldSession': 'Available sessions',
    'customer.fieldStart': 'Start time',
    'customer.fieldEnd': 'End time',
    'customer.slotOccupied': 'Occupied',
    'customer.slotPast': 'Past slot',
    'customer.slotSelected': 'Selected slot',
    'customer.slotChooseDateEmployee': 'Choose employee and day to see the timetable.',
    'customer.selectService': 'Select service',
    'customer.selectEmployee': 'Select employee',
    'customer.selectLocation': 'Select location',
    'customer.noAddress': 'No address listed',
    'customer.loggedCustomer': 'Signed-in customer',
    'customer.confirmReservation': 'Confirm reservation',
    'customer.myReservations': 'My reservations',
    'customer.myReservationsLead': 'Track upcoming visits and cancel when needed.',
    'customer.reservationsWord': 'reservations',
    'customer.noReservations': 'No reservations yet.',
    'customer.membershipUpgrade': 'Membership upgrade',
    'customer.membershipUpgradeLead': 'Request premium access for priority scheduling.',
    'customer.adminReview': 'Admin review',
    'customer.vipApprovedTitle': 'Approved',
    'customer.vipApprovedLead': 'You already have VIP access.',
    'customer.vipPendingTitle': 'Pending',
    'customer.vipPendingLead': 'Your VIP request is under review.',
    'customer.vipRejectedTitle': 'Not approved',
    'customer.vipRejectedLead': 'You can apply again with more details.',
    'customer.vipReason': 'Reason for VIP request',
    'customer.vipPlaceholder': 'Share preferred services or schedule needs.',
    'customer.sendVip': 'Submit request',
    'customer.cancel': 'Cancel',
    'customer.date': 'Date',
    'customer.location': 'Location',
    'customer.with': 'with',
    'customer.errorRequired': 'Please complete all required fields.',
    'customer.errorBookingFailed': 'Booking failed. Please try again.',
    'customer.bookingCreated': 'Your reservation has been confirmed.',
    'customer.errorGuestBooking': 'Booking is available after signing in.',
    'customer.errorVipLogin': 'You must be signed in to apply for VIP.',
    'customer.errorVipNote': 'Add a short note to your VIP request.',
    'customer.confirmCancel': 'Cancel this reservation?',

    'employee.eyebrow': 'Team Schedule',
    'employee.title': 'Service calendar',
    'employee.lead': 'Track upcoming appointments and stay prepared.',
    'employee.employee': 'Employee',
    'employee.teamMember': 'Team member',
    'employee.view': 'View',
    'employee.upcomingView': 'Upcoming only',
    'employee.allView': 'All bookings',
    'employee.filterUpcoming': 'Upcoming only',
    'employee.filterAll': 'All bookings',
    'employee.noBookings': 'No bookings found for this schedule.',
    'employee.customer': 'Customer',
    'employee.location': 'Location',
    'employee.window': 'Window',
    'employee.remaining': 'Time remaining',

    'admin.eyebrow': 'Operations Center',
    'admin.title': 'System administration',
    'admin.lead': 'Manage access, users, and approvals.',
    'admin.roles': 'Roles',
    'admin.users': 'Users',
    'admin.vipRequests': 'VIP requests',
    'admin.roleAndViews': 'Roles & Views',
    'admin.userOverview': 'User Overview',
    'admin.vipTab': 'VIP Requests',
    'admin.createAdminTab': 'Create Admin',
    'admin.usersTab': 'Users',
    'admin.bookingsTab': 'Bookings',
    'admin.servicesTab': 'Services',
    'admin.locationsTab': 'Locations',
    'admin.refresh': 'Refresh',
    'admin.partialLoad': 'Some sections failed to load. Please refresh.',
    'admin.roleManagement': 'Role management',
    'admin.cancel': 'Cancel',
    'admin.addRole': 'Add new role',
    'admin.roleName': 'Role name',
    'admin.roleNamePlaceholder': 'e.g. CUSTOMER_PLUS',
    'admin.roleView': 'Role view',
    'admin.description': 'Description',
    'admin.noDescription': 'No description',
    'admin.adminAccess': 'Admin access',
    'admin.createRole': 'Create role',
    'admin.updateRole': 'Update role',
    'admin.requiredRoleFields': 'Complete required role fields.',
    'admin.roleSaveFailed': 'Role save failed.',
    'admin.roleSaved': 'Role saved successfully.',
    'admin.roleDeleted': 'Role deleted successfully.',
    'admin.roleDeleteFailed': 'Role could not be deleted.',
    'admin.roleDescriptionPlaceholder': 'Short role description',
    'admin.yes': 'Yes',
    'admin.no': 'No',
    'admin.actions': 'Actions',
    'admin.assignedView': 'Assigned View',
    'admin.vip': 'VIP',
    'admin.edit': 'Edit',
    'admin.delete': 'Delete',
    'admin.areYouSure': 'Are you sure?',
    'admin.noPendingVip': 'No pending VIP requests.',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.vipApprovedToast': 'VIP request approved.',
    'admin.vipRejectedToast': 'VIP request rejected.',
    'admin.createAdmin': 'Create new admin',
    'admin.username': 'Username',
    'admin.password': 'Password',
    'admin.name': 'Name',
    'admin.email': 'Email',
    'admin.phone': 'Phone',
    'admin.createAdminBtn': 'Create admin',
    'admin.completeAdminFields': 'Complete all admin fields.',
    'admin.createAdminFailed': 'Admin creation failed.',
    'admin.adminCreated': 'Admin created successfully.',
    'admin.editUser': 'Edit user',
    'admin.addUser': 'Add user',
    'admin.createUser': 'Create new user',
    'admin.createUserBtn': 'Create user',
    'admin.roleLabel': 'Role',
    'admin.selectRole': 'Select role',
    'admin.passwordOptional': 'New password (optional)',
    'admin.passwordOptionalHint': 'Leave empty to keep unchanged',
    'admin.completeUserFields': 'Complete all required user fields.',
    'admin.updateUser': 'Save user',
    'admin.userSaved': 'User saved successfully.',
    'admin.userSaveFailed': 'User save failed.',
    'admin.userDeleted': 'User deleted successfully.',
    'admin.userDeleteFailed': 'User could not be deleted.',
    'admin.bookingsManager': 'Bookings management',
    'admin.customer': 'Customer',
    'admin.employee': 'Employee',
    'admin.serviceLabel': 'Service',
    'admin.locationLabel': 'Location',
    'admin.selectCustomer': 'Select customer',
    'admin.selectEmployee': 'Select employee',
    'admin.selectService': 'Select service',
    'admin.selectLocation': 'Select location',
    'admin.completeBookingFields': 'Complete all booking fields.',
    'admin.createBooking': 'Create booking',
    'admin.updateBooking': 'Update booking',
    'admin.bookingSaved': 'Booking saved successfully.',
    'admin.bookingSaveFailed': 'Booking save failed.',
    'admin.confirmDeleteBooking': 'Delete this booking?',
    'admin.bookingDeleted': 'Booking deleted successfully.',
    'admin.bookingDeleteFailed': 'Booking could not be deleted.',
    'admin.servicesManager': 'Services management',
    'admin.serviceName': 'Service name',
    'admin.price': 'Price',
    'admin.vipOnly': 'VIP only',
    'admin.completeServiceFields': 'Complete all service fields.',
    'admin.createService': 'Create service',
    'admin.updateService': 'Update service',
    'admin.serviceSaved': 'Service saved successfully.',
    'admin.serviceSaveFailed': 'Service save failed.',
    'admin.confirmDeleteService': 'Delete this service?',
    'admin.serviceDeleted': 'Service deleted successfully.',
    'admin.serviceDeleteFailed': 'Service could not be deleted.',
    'admin.priceChartSelect': 'Select price chart PDF',
    'admin.priceChartUpload': 'Upload PDF',
    'admin.priceChartDownload': 'Download PDF',
    'admin.priceChartOnlyPdf': 'Only PDF files are allowed.',
    'admin.priceChartPickFile': 'Pick a PDF file to upload.',
    'admin.priceChartUploadSuccess': 'Price chart uploaded successfully.',
    'admin.priceChartUploadFailed': 'Price chart upload failed.',
    'admin.priceChartNotFound': 'No uploaded price chart found.',
    'admin.locationsManager': 'Locations management',
    'admin.locationName': 'Location name',
    'admin.locationAddress': 'Address',
    'admin.noAddress': 'No address provided',
    'admin.vipServicesAvailable': 'VIP services available',
    'admin.completeLocationFields': 'Complete all location fields.',
    'admin.createLocation': 'Create location',
    'admin.updateLocation': 'Update location',
    'admin.locationSaved': 'Location saved successfully.',
    'admin.locationSaveFailed': 'Location save failed.',
    'admin.confirmDeleteLocation': 'Delete this location?',
    'admin.locationDeleted': 'Location deleted successfully.',
    'admin.locationDeleteFailed': 'Location could not be deleted.',

    'vip.tag': 'Premium Portal',
    'vip.title': 'Priority access',
    'vip.lead': 'Book with member pricing and priority slots.',
    'vip.member': 'Member',
    'vip.guest': 'VIP Guest',
    'vip.discount': 'Discount',
    'vip.downloadMenu': 'Download menu',
    'vip.newReservation': 'New premium reservation',
    'vip.newReservationLead': 'Select service, employee, and location.',
    'vip.reserve': 'Reserve slot',
    'vip.premiumServices': 'Premium services',
    'vip.premiumServicesLead': 'Member pricing is applied to all services.',
    'vip.servicesWord': 'services',
    'vip.myReservations': 'My reservations',
    'vip.myReservationsLead': 'Your upcoming premium bookings.',
    'vip.reservedWord': 'reserved',
    'vip.none': 'No premium reservations yet.',
    'vip.save': 'Save',
    'vip.badge': 'VIP',
    'vip.completeFields': 'Complete all booking fields.',
    'vip.bookingFailed': 'Booking failed. Please try again.',
    'vip.cancelConfirm': 'Cancel this booking?',
    'vip.priceChartUnavailable': 'Price chart is not uploaded yet.',

    'redirect.preparing': 'Preparing your profile...'
  }
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private languageSubject = new BehaviorSubject<AppLanguage>('bg');
  readonly language$ = this.languageSubject.asObservable();

  constructor() {
    if (typeof window !== 'undefined') {
      const stored = window.localStorage.getItem(STORAGE_KEY) as AppLanguage | null;
      if (stored === 'bg' || stored === 'en') {
        this.languageSubject.next(stored);
      }
      document.documentElement.lang = this.languageSubject.value;
    }
  }

  get currentLanguage(): AppLanguage {
    return this.languageSubject.value;
  }

  setLanguage(language: AppLanguage): void {
    this.languageSubject.next(language);
    if (typeof window !== 'undefined') {
      window.localStorage.setItem(STORAGE_KEY, language);
      document.documentElement.lang = language;
    }
  }

  t(key: string): string {
    const lang = this.currentLanguage;
    return TRANSLATIONS[lang][key] ?? TRANSLATIONS.bg[key] ?? key;
  }
}
